[character]
error_symbol = "[✗](bold red) "

#[java]
#format = "[${symbol}(${version} )]($style)"
#style = "bold blue"
#
#[kotlin]
#format = "[$symbol($version )]($style)"
#style = "bold blue"

[git_branch]
symbol = '🌱 '
format = "[$symbol$branch]($style) "

[battery]
disabled = false

[cmd_duration]
min_time = 10_000  # Show command duration over 10,000 milliseconds (=10 sec)
format = " took [$duration]($style)"

[directory]
truncation_length = 5
format = "[$path]($style)[$lock_symbol]($lock_style) "
read_only = '🔒'

[git_commit]
commit_hash_length = 8
#style = "bold white"

#[git_state]
#format = '[\($state( $progress_current of $progress_total)\)]($style) '

[hostname]
ssh_only = false
format = "[$hostname]($style)"
trim_at = "-"
style = "bold dimmed white"
disabled = true

[python]
format = "[$symbol$version]($style)( ($virtualenv) )"
#format = "via [${symbol}${pyenv_prefix}(${version} )(\(\${virtualenv}\)\)]($style)"
style = "bold green"

[username]
style_user = "bold dimmed green"
show_always = true 


#[time]
#format = "at [$time]($style) "
#style = "bold yellow"
#disabled = false

#[line_break]
#disabled = false
[nodejs]
disabled = true
